spring:
  mail:
    host: smtp.qq.com
    username: 594207613
    password: vvhxpbootyjjbfhh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  zju-login-client:
    pubkey-url: https://zjuam.zju.edu.cn/cas/v2/getPubKey
    login-url: https://zjuam.zju.edu.cn/cas/login
    cookie-cached: false
  health-report-client:
    report-url: https://healthreport.zju.edu.cn/ncov/wap/default/index
    submit-url: https://healthreport.zju.edu.cn/ncov/wap/default/save
    code-url: https://healthreport.zju.edu.cn/ncov/wap/default/code
  mail:
    domain: qq.com
    from: ${spring.mail.username}@${app.mail.domain}
    nickname: 健康打卡服务
  cron: "0 0 8 * * ? *"
  mode: 1   # 0: work,  1: work once,  2: test,  3: test once